version: "3.5"
services:
  todo-mysql:
    volumes:
      - "/Users/hitenpratap/Desktop/30th-Apr/mysql-data:/var/lib/mysql"
    ports:
      - "3308:3306"
    networks:
      - techcret
    container_name: todo-mysql
    image: docker.pkg.github.com/techcret/spring-boot-todo/todo-mysql:1.0
  todo-app:
    ports:
      - "7310:7310"
    container_name: todo-app
    networks:
      - techcret
    image: docker.pkg.github.com/techcret/spring-boot-todo/todo-app:1.0
    depends_on:
      - todo-mysql

networks:
  techcret:
    name: techcret
