server:
  port: 7310

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://todo-mysql:3306/spring_todo_mvc
    username: root
    password: Test-123
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
  thymeleaf:
    cache: false